Willian/Models/EnviarEmail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Willian.Models
{
    public class EnviarEmail
    {
        [Required(ErrorMessage = "* Por favor Digite um Nome")]
        [MinLength(3, ErrorMessage = "* Mínimo 3 caracteres")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "* Por favor Digite um Email")]
        [MinLength(5, ErrorMessage = "* Mínimo 3 caracteres")]
        [EmailAddress(ErrorMessage = "* Formato de Email inválido")]
        public string Email { get; set; }
        [MinLength(5, ErrorMessage = "* Mínimo 5 caracteres")]
        public string Mensagem { get; set; }
    }
}

Willian/Models/ErrorViewModel.cs
using System;

namespace Willian.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Willian/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Willian.Models;

namespace Willian.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Sobre()
        {
            return View();
        }

        public IActionResult Portifolio()
        {
            return View();
        }

        public IActionResult Contato()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Willian/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Willian.Models;

namespace Willian.Controllers
{
    public class SiteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Sobre()
        {
            return View();
        }

        public IActionResult Portifolio()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Contato()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Contato(EnviarEmail enviarEmail)
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Willian/Views/Home/Sobre.cshtml
@{
    ViewData["Title"] = "Sobre";
}
<link rel="stylesheet" href="~/css/sobre.css"/>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="w-titulo">
                <h2 class="ml-2 mt-5">@ViewData["Title"]</h2>
                <p class="ml-2">Principais informações sobre mim</p>
            </div>
        </div>
        
    </div>

    <div class="row">
        <div class="col-md-4">
            <img src="~/imagens/wire.png" class="img-fluid w-img-pessoal" />
        </div>
        <div class="col-md-6">
            <h2 class="w-nome">Eu sou Willian Bello e <span class="w-cf-orange-3">Desenvolvedor Web</span></h2>
            <p class="w-paragrafo">
                Olá, meu nome é Willian Bello, sou desenvolvedor web muito apaixonado e dedicado eu meu trabalho.
                Tenho mais ou menos 6 meses de experiência com desenvolvimento HTML5, CSS3, Bootstrap 4, Javascript e jQuery.
                Adquiri minhas habilidades trabalhando em projetos pessoais e contribuindo em diversos projetos de amigos.
                Me dedico a aprendizagem e aprimoramento de novas tecnologias buscando desafios a serem superados.
            </p>
            <div class="row">
                <div class="col-md-6">
                    <p class="w-paragrafo2"><span class="w-categoria">Aniversário: </span>10.12.1990</p>
                    <p class="w-paragrafo2"><span class="w-categoria">Cidade: </span>Gravataí - RS</p>
                    <p class="w-paragrafo2"><span class="w-categoria">Escolaridade: </span>Bacharel em Ciência da Computação (em andamento)</p>
                    <p class="w-paragrafo2"><span class="w-categoria">Telefone: </span>(51) 99456-5618</p>
                    <button class="btn w-bg-orange-3 w-cf-white">Enviar mensagem</button>
                </div>

                <div class="col-md-6">
                    <p class="w-paragrafo2"><span class="w-categoria">Idade: </span>28 anos</p>
                    <p class="w-paragrafo2"><span class="w-categoria">Interesses: </span>Musica, Artes Marciais</p>
                    <p class="w-paragrafo2"><span class="w-categoria">Email: </span>willianbello.s@gmail.com</p>
                    <p class="w-paragrafo2"><span class="w-categoria">Página Facebook: </span>-------</p>
                </div>
            </div>

        </div>
        
    </div>

    
</div>

Willian/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Willian</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/cores.css" />
    <link rel="stylesheet" href="~/css/home.css" />
    <link rel="stylesheet" href="~/css/contato.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
    <link href="https://fonts.googleapis.com/css?family=Merienda|Merriweather|Playfair+Display+SC|Prata" rel="stylesheet">
</head>
<body>
    <header class=" w-bg-azul-3 fixed-top w-altura-menu">
        <div class="container">
            <nav class="navbar navbar-expand-lg mt-auto mb-auto">
                <a class="navbar-brand" asp-action="Index"><img src="~/imagens/logo2.png" class="img-fluid w-logo-site"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto w-menu-topo-fixo">
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index">HOME <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item ml-2">
                            <a class="nav-link" asp-action="Sobre">SOBRE</a>
                        </li>
                        <li class="nav-item ml-2">
                            <a class="nav-link" asp-action="Portifolio">PORTIFÓLIO</a>
                        </li>
                        <li class="nav-item ml-2">
                            <a class="nav-link" asp-action="Contato">CONTATO</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <div class="w-altura-menu"></div>
    <div> 
        <partial name="_CookieConsentPartial" />
        <main role="main">
            @RenderBody()
        </main>
    </div>
    

    <footer class="border-top footer w-cf-white w-bg-azul-3">
        <div class="container text-center">
            &copy; 2019 - Willian - <span asp-controller="Home" asp-action="Index" style="color:#CC8D09">Todos os Direitos Reservados</span>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Willian/Views/Site/Contato.cshtml
<link rel="stylesheet" href="~/css/sobre.css" />
@model Willian.Models.EnviarEmail;

@{
    ViewData["Title"] = "Contato";
}

<link rel="stylesheet" href="~/css/sobre.css" />
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="w-titulo">
                <h2 class="ml-2 mt-5">@ViewData["Title"]</h2>
            </div>
        </div>

        <div class="col-md-5 ml-2">
            <form asp-controller="Site" asp-action="Contato" method="post">
                <div class="form-group">
                    <div class="form-group row">
                        <label for="Nome" class="col-form-label">Nome:</label>
                        <input type="text" class="form-control" asp-for="Nome" aria-describedby="Nome" placeholder="Digite aqui seu Nome...">
                        <span asp-validation-for="Nome" class="text-danger w-font-erro"></span>
                    </div>
                    <div class="form-group row">
                        <label for="Email" class="col-form-label">Email:</label>
                        <input type="email" class="form-control" asp-for="Email" aria-describedby="Email" placeholder="Digite aqui seu e-mail...">
                        <span asp-validation-for="Email" class="text-danger w-font-erro"></span>
                    </div>
                    <div class="form-group row">
                        <label form="Mensagem" class="col-form-label">Mensagem</label>
                        <input type="text" class="form-control" asp-for="Mensagem" aria-describedby="Mensagem" placeholder="Digite aqui sua Mensagem...">
                        <span asp-validation-for="Mensagem" class="text-danger w-font-erro"></span>
                    </div>
                    <div class="row">
                        <button type="submit" class="btn btn-warning">Enviar Mensagem</button>
                    </div>
                    
                </div>
                
            </form>
        </div>
    </div>
</div>

Willian/Views/Site/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<head>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js"></script>
</head>

<script>
    
</script>

<div class="text-center w-fundo-home w-height">
    <section>
        <div class="row">
            <div class="col-md-12 w-margin-img">
                <img src="~/imagens/perfil2.png" class="img-fluid rounded-circle w-borda-img" />
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-md-12">
                <h2 class="w-fs-40 w-cf-white animated flipInX" style="animation-duration:2s">WILLIAN <span class="w-cf-orange-2"> BELLO</span></h2>
                <div class="w-cf-white w-fs-20 mt-3">
                    <p id="texto1">Desenvolvedor Web</p>
                    <p id="texto2">Freelancer</p>
                    <p id="texto3">UX/UI Design</p>
                </div>
            </div>
        </div>
    </section>
    
</div>

Willian/Views/Site/Portifolio.cshtml
@{
    ViewData["Title"] = "Portifólio";
}
<h1>@ViewData["Title"]</h1>

<p>Portifólios do Github</p>

Willian/Views/Site/Sobre.cshtml
@{
    ViewData["Title"] = "Sobre";
}

<link rel="stylesheet" href="~/css/sobre.css"/>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="w-titulo">
                <h2 class="ml-2 mt-5">@ViewData["Title"]</h2>
                <p class="ml-2">Principais informações sobre mim</p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <img src="~/imagens/wire.png" class="img-fluid w-img-pessoal" />
        </div>
        <div class="col-md-6">
            <h2 class="w-nome">Eu sou Willian Bello e <span class="w-cf-orange-3">Desenvolvedor Web</span></h2>
            <p class="w-paragrafo">
                Olá, meu nome é Willian Bello, sou desenvolvedor web muito apaixonado e dedicado eu meu trabalho.
                Tenho mais ou menos 6 meses de experiência com desenvolvimento HTML5, CSS3, Bootstrap 4, Javascript e jQuery.
                Adquiri minhas habilidades trabalhando em projetos pessoais e contribuindo em diversos projetos de amigos.
                Me dedico a aprendizagem e aprimoramento de novas tecnologias buscando desafios a serem superados.
            </p>
            <div class="row">
                <div class="col-md-6">
                    <p class="w-paragrafo2"><span class="w-categoria">Aniversário: </span>10.12.1990</p>
                    <p class="w-paragrafo2"><span class="w-categoria">Cidade: </span>Gravataí - RS</p>
                    <p class="w-paragrafo2"><span class="w-categoria">Escolaridade: </span>Bacharel em Ciência da Computação (em andamento)</p>
                    <p class="w-paragrafo2"><span class="w-categoria">Telefone: </span>(51) 99456-5618</p>
                    <button class="btn w-bg-orange-3 w-cf-white">Enviar mensagem</button>
                </div>

                <div class="col-md-6">
                    <p class="w-paragrafo2"><span class="w-categoria">Idade: </span>28 anos</p>
                    <p class="w-paragrafo2"><span class="w-categoria">Interesses: </span>Musica, Artes Marciais</p>
                    <p class="w-paragrafo2"><span class="w-categoria">Email: </span>willianbello.s@gmail.com</p>
                    <p class="w-paragrafo2"><span class="w-categoria">Página Facebook: </span>-------</p>
                </div>
            </div>
        </div>
    </div>

    

</div>